"use client";

import { useActionState, useEffect } from "react";
import {
  registerStudent,
  type RegisterStudentFormState,
} from "@/lib/academies/register-student-actions";
import { Button, ErrorMessage, Field, inputClass } from "@/app/academy/_shell/ui";
import { showErrorToast, showInfoToast, showSuccessToast } from "@/lib/ui/toast";

const initialState: RegisterStudentFormState = { ok: false };

interface StudentFormProps {
  /** Already scoped to what the caller may register into — see
   * app/academy/students/new/page.tsx's module comment. */
  branches: { id: string; name: string }[];
  /**
   * "Course" selection — each option IS a specific batch (a course's
   * schedule offering), labeled "{course name} — {batch name}" so it reads
   * as picking a course even though the underlying enrollment
   * (batch_enrollments) requires a specific batch. This preserves the
   * existing Student -> Batch -> Course architecture rather than inventing
   * a direct student<->course relationship. Optional: a student can be
   * registered without a course and enrolled later from the batch roster.
   */
  courseOptions: { batchId: string; label: string }[];
}

/**
 * PLAN.md Item 38 / `/academy/students/new`. The student number
 * (`STD-000001`, ...) is never a form field — it's server-generated by
 * `generateStudentId` inside `registerStudent`, never client-supplied.
 */
export function StudentForm({ branches, courseOptions }: StudentFormProps) {
  const [state, formAction, pending] = useActionState(registerStudent, initialState);

  useEffect(() => {
    if (state.ok && state.enrollmentWarning) {
      showInfoToast(state.enrollmentWarning);
    } else if (state.ok) {
      showSuccessToast("Student registered.");
    } else if (state.error) {
      showErrorToast(state.error.message);
    }
  }, [state]);

  return (
    <form action={formAction} className="flex flex-col gap-3">
      <Field label="Branch">
        <select name="branchId" required defaultValue="" className={inputClass}>
          <option value="" disabled>
            Select a branch
          </option>
          {branches.map((branch) => (
            <option key={branch.id} value={branch.id}>
              {branch.name}
            </option>
          ))}
        </select>
      </Field>
      <Field label="Full name">
        <input type="text" name="fullName" required className={inputClass} />
      </Field>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <Field label="Date of birth">
          <input type="date" name="dateOfBirth" className={inputClass} />
        </Field>
        <Field label="Gender">
          <input type="text" name="gender" className={inputClass} />
        </Field>
      </div>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <Field label="Phone">
          <input type="text" name="phone" className={inputClass} />
        </Field>
        <Field label="Email">
          <input type="email" name="email" className={inputClass} />
        </Field>
      </div>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <Field label="Guardian name">
          <input type="text" name="guardianName" className={inputClass} />
        </Field>
        <Field label="Guardian phone">
          <input type="text" name="guardianPhone" className={inputClass} />
        </Field>
      </div>
      <Field label="Course">
        <select name="batchId" defaultValue="" className={inputClass}>
          <option value="">No course selected yet</option>
          {courseOptions.map((option) => (
            <option key={option.batchId} value={option.batchId}>
              {option.label}
            </option>
          ))}
        </select>
      </Field>

      {state.error && <ErrorMessage message={state.error.message} />}
      {state.enrollmentWarning && (
        <p role="alert" className="rounded-control border border-warning/30 bg-warning-bg px-3 py-2 text-sm text-warning">
          {state.enrollmentWarning}
        </p>
      )}
      {state.ok && !state.enrollmentWarning && (
        <p className="text-sm font-medium text-success">Student registered.</p>
      )}

      <Button type="submit" disabled={pending} className="self-start">
        {pending ? "Registering..." : "Register student"}
      </Button>
    </form>
  );
}
