"use client";

import { useActionState, useEffect, useState } from "react";
import {
  registerStudent,
  type RegisterStudentFormState,
} from "@/lib/academies/register-student-actions";
import { Button, ErrorMessage, Field, inputClass } from "@/app/academy/_shell/ui";
import { showErrorToast, showInfoToast, showSuccessToast } from "@/lib/ui/toast";
import { StudentPhotoField } from "@/app/academy/students/student-photo-field";

const initialState: RegisterStudentFormState = { ok: false };

/** Mirrors lib/db/schema.ts's FEE_INTERVAL_MONTHS_OPTIONS — same list as
 * app/academy/batches/[batchId]/roster-panel.tsx's enroll form. */
const PAYMENT_PLAN_INTERVAL_OPTIONS: { value: number; label: string }[] = [
  { value: 1, label: "Monthly" },
  { value: 2, label: "Every 2 Months" },
  { value: 3, label: "Every 3 Months" },
  { value: 4, label: "Every 4 Months" },
  { value: 6, label: "Every 6 Months" },
  { value: 12, label: "Yearly" },
];

interface StudentFormProps {
  /** Already scoped to what the caller may register into — see
   * app/academy/students/new/page.tsx's module comment. */
  branches: { id: string; name: string }[];
  /**
   * "Course" selection — each option IS a specific batch (a course's
   * schedule offering), labeled "{course name} — {batch name}" so it reads
   * as picking a course even though the underlying enrollment
   * (batch_enrollments) requires a specific batch. This preserves the
   * existing Student -> Batch -> Course architecture rather than inventing
   * a direct student<->course relationship. Optional: a student can be
   * registered without a course and enrolled later from the batch roster.
   */
  courseOptions: { batchId: string; label: string }[];
}

/** Small uppercase group label, matching the existing
 * `uppercase tracking-wide text-muted text-xs` convention already used for
 * field labels on the student's own detail page (`InfoField`/`SummaryStat`
 * in student-detail.tsx) — groups this form's ~9 fields into Identity /
 * Contact / Guardian / Enrollment instead of one undifferentiated stack. */
function FormGroup({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-3">
      <p className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</p>
      {children}
    </div>
  );
}

/**
 * PLAN.md Item 38 / `/academy/students/new`. The student number
 * (`STD-000001`, ...) is never a form field — it's server-generated by
 * `generateStudentId` inside `registerStudent`, never client-supplied.
 */
export function StudentForm({ branches, courseOptions }: StudentFormProps) {
  const [state, formAction, pending] = useActionState(registerStudent, initialState);
  const [selectedBatchId, setSelectedBatchId] = useState("");
  // Bumped on every successful registration — passed as StudentPhotoField's
  // own `key` below so it fully remounts (clearing its uploaded-photo-key
  // state) rather than silently resubmitting the SAME already-uploaded
  // photo onto whatever student this form registers next. The rest of
  // this form's plain inputs have the same "doesn't reset after success"
  // characteristic already (a pre-existing gap, not introduced here) —
  // only the photo field needed fixing, since reusing a stale value there
  // would wrongly attach one photo to multiple students, not just leave
  // stale text in a field.
  //
  // Bumped during render (react.dev's "adjust state when a prop changes"
  // pattern — see students-list.tsx's identical prevEditingId/prevOpen
  // uses), not inside the toast effect below: setState directly inside an
  // effect body risks a cascading extra render, which this codebase
  // avoids throughout.
  const [formVersion, setFormVersion] = useState(0);
  const [prevStateOk, setPrevStateOk] = useState(state.ok);
  if (state.ok !== prevStateOk) {
    setPrevStateOk(state.ok);
    if (state.ok) setFormVersion((v) => v + 1);
  }

  useEffect(() => {
    if (state.ok && state.enrollmentWarning) {
      showInfoToast(state.enrollmentWarning);
    } else if (state.ok) {
      showSuccessToast("Student registered.");
    } else if (state.error) {
      showErrorToast(state.error.message);
    }
  }, [state]);

  return (
    <form action={formAction} className="flex flex-col gap-6">
      <FormGroup label="Identity">
        <StudentPhotoField key={formVersion} mode="new" hiddenFieldName="profileImageRef" />
        <Field label="Branch">
          <select name="branchId" required defaultValue="" className={inputClass}>
            <option value="" disabled>
              Select a branch
            </option>
            {branches.map((branch) => (
              <option key={branch.id} value={branch.id}>
                {branch.name}
              </option>
            ))}
          </select>
        </Field>
        <Field label="Full name">
          <input type="text" name="fullName" required className={inputClass} />
        </Field>
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <Field label="Date of birth">
            <input type="date" name="dateOfBirth" className={inputClass} />
          </Field>
          <Field label="Gender">
            <input type="text" name="gender" className={inputClass} />
          </Field>
        </div>
        <p className="text-xs text-muted">
          A unique student ID (e.g. STD-000123) is generated automatically on save.
        </p>
      </FormGroup>

      <FormGroup label="Contact">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <Field label="Phone">
            <input type="text" name="phone" className={inputClass} />
          </Field>
          <Field label="Email">
            <input type="email" name="email" className={inputClass} />
          </Field>
        </div>
      </FormGroup>

      <FormGroup label="Guardian">
        <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <Field label="Guardian name">
            <input type="text" name="guardianName" className={inputClass} />
          </Field>
          <Field label="Guardian phone">
            <input type="text" name="guardianPhone" className={inputClass} />
          </Field>
        </div>
      </FormGroup>

      <FormGroup label="Enrollment (optional)">
        <Field label="Course">
          <select
            name="batchId"
            value={selectedBatchId}
            onChange={(event) => setSelectedBatchId(event.target.value)}
            className={inputClass}
          >
            <option value="">No course selected yet</option>
            {courseOptions.map((option) => (
              <option key={option.batchId} value={option.batchId}>
                {option.label}
              </option>
            ))}
          </select>
        </Field>

        {selectedBatchId && (
          <div className="grid grid-cols-1 gap-3 rounded-control border border-border bg-app p-3 sm:grid-cols-2">
            <Field label="Payment Plan">
              <select name="paymentPlanIntervalMonths" required defaultValue="1" className={inputClass}>
                {PAYMENT_PLAN_INTERVAL_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>
                    {option.label}
                  </option>
                ))}
              </select>
            </Field>
            <Field label="Amount per period (USD)">
              <input type="number" name="paymentPlanAmountDollars" min={0.01} step="0.01" placeholder="0.00" required className={inputClass} />
            </Field>
          </div>
        )}
      </FormGroup>

      {state.error && <ErrorMessage message={state.error.message} />}
      {state.enrollmentWarning && (
        <p role="alert" className="rounded-control border border-warning/30 bg-warning-bg px-3 py-2 text-sm text-warning">
          {state.enrollmentWarning}
        </p>
      )}
      {state.ok && !state.enrollmentWarning && (
        <p className="text-sm font-medium text-success">Student registered.</p>
      )}

      <Button type="submit" disabled={pending} className="self-start">
        {pending ? "Registering..." : "Register student"}
      </Button>
    </form>
  );
}
