"use client";

import { useActionState } from "react";
import {
  registerStudent,
  type RegisterStudentFormState,
} from "@/lib/academies/register-student-actions";

const initialState: RegisterStudentFormState = { ok: false };

interface StudentFormProps {
  /** Already scoped to what the caller may register into — see
   * app/academy/students/new/page.tsx's module comment. */
  branches: { id: string; name: string }[];
  /**
   * "Course" selection — each option IS a specific batch (a course's
   * schedule offering), labeled "{course name} — {batch name}" so it reads
   * as picking a course even though the underlying enrollment
   * (batch_enrollments) requires a specific batch. This preserves the
   * existing Student -> Batch -> Course architecture rather than inventing
   * a direct student<->course relationship. Optional: a student can be
   * registered without a course and enrolled later from the batch roster.
   */
  courseOptions: { batchId: string; label: string }[];
}

/**
 * PLAN.md Item 38 / `/academy/students/new`. The student number
 * (`STD-000001`, ...) is never a form field — it's server-generated by
 * `generateStudentId` inside `registerStudent`, never client-supplied.
 */
export function StudentForm({ branches, courseOptions }: StudentFormProps) {
  const [state, formAction, pending] = useActionState(registerStudent, initialState);

  return (
    <form
      action={formAction}
      style={{ display: "flex", flexDirection: "column", gap: "0.75rem", maxWidth: 420 }}
    >
      <label>
        Branch
        <select name="branchId" required defaultValue="" style={{ display: "block", width: "100%" }}>
          <option value="" disabled>
            Select a branch
          </option>
          {branches.map((branch) => (
            <option key={branch.id} value={branch.id}>
              {branch.name}
            </option>
          ))}
        </select>
      </label>
      <label>
        Full name
        <input type="text" name="fullName" required style={{ display: "block", width: "100%" }} />
      </label>
      <label>
        Date of birth
        <input type="date" name="dateOfBirth" style={{ display: "block", width: "100%" }} />
      </label>
      <label>
        Gender
        <input type="text" name="gender" style={{ display: "block", width: "100%" }} />
      </label>
      <label>
        Phone
        <input type="text" name="phone" style={{ display: "block", width: "100%" }} />
      </label>
      <label>
        Email
        <input type="email" name="email" style={{ display: "block", width: "100%" }} />
      </label>
      <label>
        Guardian name
        <input type="text" name="guardianName" style={{ display: "block", width: "100%" }} />
      </label>
      <label>
        Guardian phone
        <input type="text" name="guardianPhone" style={{ display: "block", width: "100%" }} />
      </label>
      <label>
        Course
        <select name="batchId" defaultValue="" style={{ display: "block", width: "100%" }}>
          <option value="">No course selected yet</option>
          {courseOptions.map((option) => (
            <option key={option.batchId} value={option.batchId}>
              {option.label}
            </option>
          ))}
        </select>
      </label>

      {state.error && (
        <p role="alert" style={{ color: "crimson" }}>
          {state.error.message}
        </p>
      )}
      {state.enrollmentWarning && (
        <p role="alert" style={{ color: "#b45309" }}>
          {state.enrollmentWarning}
        </p>
      )}
      {state.ok && !state.enrollmentWarning && <p style={{ color: "green" }}>Student registered.</p>}

      <button type="submit" disabled={pending}>
        {pending ? "Registering..." : "Register student"}
      </button>
    </form>
  );
}
