import { randomBytes } from "node:crypto";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { db, type DbClient } from "@/lib/db";
import {
  batches,
  certificates,
  certificateVerifications,
  courses,
  examResults,
  gradeBands,
  programs,
  students,
} from "@/lib/db/schema";
import { checkAcademyAccessForContext } from "@/lib/academies/access-gate";
import { checkCertificateVerifyRateLimit } from "@/lib/academies/certificate-verify-rate-limit";
import {
  ACADEMY_CERTIFICATES_ACTION,
  getAcademyPermissionLevel,
  type AcademyPermissionLevel,
} from "@/lib/auth/academy-permissions";
import { evaluateGradeBand } from "@/lib/academies/results";
import { recordAudit } from "@/lib/audit";
import type { AuthContext } from "@/lib/auth/auth-context";
import type { AcademyRole } from "@/lib/auth/roles";

/**
 * PLAN.md Phase 5, Item 57 — "`issueCertificate` (eligibility: published
 * Pass result required in that batch)/`cancelCertificate`
 * (`/academy/certificates`)." Item 62's public `verifyCertificate` lives
 * here too (rather than a separate file) — it shares the same
 * `certificates`/`certificate_verifications` tables and this is the only
 * place either is touched.
 *
 * ---------------------------------------------------------------------
 * Permission gating
 * ---------------------------------------------------------------------
 * lib/auth/academy-permissions.ts's `ACADEMY_CERTIFICATES_ACTION` row (see
 * its own module comment): Owner="full", Admin/Manager="manage",
 * Trainer="view", Admissions Officer/Finance Officer=no entry ("none").
 * `canManage`'s "full"-or-"manage" gate below is the ONLY gate
 * `issueCertificate`/`cancelCertificate` use — Trainer's "view" passes
 * neither (list/read-only), matching PLAN.md's Master Permission Matrix
 * "Certificates (issue/cancel)" row exactly (Full/Manage/Manage/—/—/View).
 *
 * ---------------------------------------------------------------------
 * Eligibility — reuses Phase 3's exact pass/fail machinery, nothing new
 * ---------------------------------------------------------------------
 * PLAN.md Phase 5: "`issueCertificate(studentId, batchId)` is server-side
 * blocked unless the given student has at least one `exam_results` row for
 * that `batch_id` with `status = published` and a `Pass` outcome under the
 * `grade_bands` active at the time that result was published (the same
 * `grade_configuration_id` snapshot already stored on the result, per Phase
 * 3)." Rather than trusting the `pass_fail` column a published row already
 * carries (set once, at publish time, by `publishResults` — see
 * lib/academies/results.ts's own comment on why that column is immutable
 * thereafter), `isStudentEligibleForCertificate` below re-derives the
 * outcome from scratch: it loads the exact `grade_bands` for the row's own
 * snapshotted `grade_configuration_id` and re-evaluates `marks_obtained`
 * against them with `evaluateGradeBand` — the same function
 * `publishResults` itself calls (imported, not reimplemented, per this
 * item's own instruction to "reuse that exact logic rather than
 * reinventing it"). This is belt-and-braces rather than strictly
 * necessary (a published row's `pass_fail` should already agree), but it
 * is what PLAN.md's own wording ("re-derive... using the same
 * grade_configuration_id snapshot") literally asks for, and it means
 * certificate eligibility never silently drifts from the grade-bands
 * mechanism even if that invariant were ever violated elsewhere.
 *
 * Any ONE published Pass result in the batch is sufficient — PLAN.md is
 * explicit that this plan defines no "final exam" concept distinct from
 * other exams, so multiple exams per batch each independently satisfy
 * eligibility on their own.
 *
 * ---------------------------------------------------------------------
 * Certificate code — opaque, non-sequential, collision-retried
 * ---------------------------------------------------------------------
 * Generated by `generateCertificateCode` (cryptographically random, drawn
 * from `randomBytes`, never a counter/sequence) and inserted inside the
 * same "fresh transaction per retry attempt" loop as
 * lib/academies/student-payments.ts's `issueReceipt`/`generateReceiptNumber`
 * — see that function's own module comment for why a caught unique
 * violation can't simply be retried inside the same (now-aborted)
 * transaction. Unlike `issueReceipt`, this loop also re-checks the
 * `(student_id, batch_id)` unique constraint explicitly at the top of every
 * attempt (`existing` lookup below) so a genuine duplicate-certificate
 * race collapses into the clean `DUPLICATE_CERTIFICATE` error on its very
 * next attempt rather than exhausting all retries — a caught unique
 * violation from the DB (via `isUniqueViolation`, same helper shape as
 * every other file in this codebase) is still the fallback path for the
 * rarer `certificate_code` collision case, per this item's own brief.
 *
 * ---------------------------------------------------------------------
 * `verifyCertificate` — intentionally NOT tenant-scoped
 * ---------------------------------------------------------------------
 * Every other lookup in this codebase resolves the caller's own academyId
 * first and scopes every query to it. This one deliberately does not:
 * PLAN.md's `/verify/[certificateCode]` is public and unauthenticated, a
 * certificate code is the sole lookup key, and the route "works unchanged
 * for closed academies" (PLAN.md Phase 5, restated in DESIGN.md §10 as a
 * "deliberate, tested distinction: closure affects the academy's own
 * console, never the public verification surface"). So this function never
 * joins against `academies`/`academy_subscriptions` at all, and a
 * suspended/closed academy's certificates verify identically to any other
 * academy's. A nonexistent code and a would-be cross-academy confusion are
 * both impossible to distinguish from the response shape (there is no
 * "wrong academy" case — the code alone determines the result), satisfying
 * the same IDOR-safe generic-response convention used everywhere else in
 * this codebase.
 *
 * A verification attempt against a code that resolves to a real
 * certificate writes a `certificate_verifications` row (audit trail per
 * PLAN.md: "verification rate-limited and logged"). An attempt against a
 * code that does NOT resolve writes nothing — logging failed lookups would
 * itself become an enumeration side channel (an attacker could infer
 * real-vs-fake codes by, e.g., timing or by later reading their own traffic
 * reflected in some future admin view of failed-verification volume);
 * PLAN.md never explicitly states this either way, so this is a documented
 * judgment call in favor of the narrower, safer logging scope.
 */
function canManage(level: AcademyPermissionLevel): boolean {
  return level === "full" || level === "manage";
}

export interface CertificateActionError {
  code:
    | "forbidden"
    | "validation"
    | "not_found"
    | "blocked"
    | "conflict"
    | "not_eligible"
    | "already_cancelled";
  message: string;
}

const FORBIDDEN: CertificateActionError = {
  code: "forbidden",
  message: "You don't have permission to view or manage this academy's certificates.",
};

const STUDENT_NOT_FOUND: CertificateActionError = {
  code: "not_found",
  message: "Student not found.",
};

const BATCH_NOT_FOUND: CertificateActionError = {
  code: "not_found",
  message: "Batch not found.",
};

const CERTIFICATE_NOT_FOUND: CertificateActionError = {
  code: "not_found",
  message: "Certificate not found.",
};

// Generic on purpose — never confirms whether the student has *some*
// exam_results in the batch vs. none at all, and never names which exam or
// grade configuration was checked (no leakage beyond "not eligible").
const NOT_ELIGIBLE: CertificateActionError = {
  code: "not_eligible",
  message:
    "This student does not yet have a published, passing result in this batch, so a certificate cannot be issued.",
};

const DUPLICATE_CERTIFICATE: CertificateActionError = {
  code: "conflict",
  message: "A certificate has already been issued to this student for this batch.",
};

const ALREADY_CANCELLED: CertificateActionError = {
  code: "already_cancelled",
  message: "This certificate has already been cancelled — cancellation is terminal.",
};

/**
 * Postgres unique_violation (23505) detection — same double-wrapped-error
 * shape as every other `isUniqueViolation` in this codebase (drizzle-orm
 * wraps the raw `pg` DatabaseError in its own `DrizzleQueryError`, so
 * `code` lives on `err.cause`, not `err` itself). Recreated locally rather
 * than imported — every other file in this codebase (branches.ts,
 * student-payments.ts, ...) defines its own copy rather than sharing one.
 */
function isUniqueViolation(err: unknown): boolean {
  if (typeof err !== "object" || err === null) return false;
  if ((err as { code?: unknown }).code === "23505") return true;
  const cause = (err as { cause?: unknown }).cause;
  return (
    typeof cause === "object" && cause !== null && (cause as { code?: unknown }).code === "23505"
  );
}

export const cancelCertificateReasonSchema = z
  .string()
  .trim()
  .min(1, "A cancellation reason is required.")
  .max(2000);

export interface CertificateRecord {
  id: string;
  academyId: string;
  studentId: string;
  batchId: string;
  certificateCode: string;
  issuedAt: Date;
  issuedBy: string;
  status: "issued" | "cancelled";
  cancelledAt: Date | null;
  cancelledBy: string | null;
  cancellationReason: string | null;
  createdAt: Date;
}

function toCertificateRecord(row: typeof certificates.$inferSelect): CertificateRecord {
  return {
    id: row.id,
    academyId: row.academyId,
    studentId: row.studentId,
    batchId: row.batchId,
    certificateCode: row.certificateCode,
    issuedAt: row.issuedAt,
    issuedBy: row.issuedBy,
    status: row.status,
    cancelledAt: row.cancelledAt,
    cancelledBy: row.cancelledBy,
    cancellationReason: row.cancellationReason,
    createdAt: row.createdAt,
  };
}

interface ResolvedCertificatesAccess {
  academyId: string;
  membershipRole: AcademyRole;
  permissionLevel: AcademyPermissionLevel;
}

type ResolveCertificatesAccessResult =
  | { ok: true; access: ResolvedCertificatesAccess }
  | { ok: false; error: CertificateActionError };

async function resolveCertificatesAccess(
  actorContext: AuthContext,
): Promise<ResolveCertificatesAccessResult> {
  const access = await checkAcademyAccessForContext(actorContext);
  if (access.level === "blocked") {
    return { ok: false, error: { code: "blocked", message: access.message } };
  }

  const permissionLevel = getAcademyPermissionLevel(
    access.membershipRole,
    ACADEMY_CERTIFICATES_ACTION,
  );
  if (permissionLevel === "none") {
    return { ok: false, error: FORBIDDEN };
  }

  return {
    ok: true,
    access: {
      academyId: access.academyId,
      membershipRole: access.membershipRole,
      permissionLevel,
    },
  };
}

interface EligibilityGradeBand {
  label: string;
  minMark: number;
  maxMark: number;
  isPass: boolean;
}

/**
 * See this file's module comment ("Eligibility") for the full derivation.
 * Loads every published `exam_results` row for this exact
 * (academy, student, batch) triple, and re-evaluates each one's own
 * snapshotted `grade_configuration_id` bands against its `marks_obtained`
 * — any single Pass is sufficient.
 */
async function isStudentEligibleForCertificate(
  executor: DbClient,
  academyId: string,
  studentId: string,
  batchId: string,
): Promise<boolean> {
  const rows = await executor
    .select({
      marksObtained: examResults.marksObtained,
      gradeConfigurationId: examResults.gradeConfigurationId,
    })
    .from(examResults)
    .where(
      and(
        eq(examResults.academyId, academyId),
        eq(examResults.studentId, studentId),
        eq(examResults.batchId, batchId),
        eq(examResults.status, "published"),
      ),
    );

  if (rows.length === 0) return false;

  const bandsByConfig = new Map<string, EligibilityGradeBand[]>();

  for (const row of rows) {
    if (row.marksObtained === null) continue; // Defensive — publishResults never leaves this null.

    let bands = bandsByConfig.get(row.gradeConfigurationId);
    if (!bands) {
      const bandRows = await executor
        .select()
        .from(gradeBands)
        .where(eq(gradeBands.gradeConfigurationId, row.gradeConfigurationId));
      bands = bandRows.map((band) => ({
        label: band.label,
        minMark: Number(band.minMark),
        maxMark: Number(band.maxMark),
        isPass: band.isPass,
      }));
      bandsByConfig.set(row.gradeConfigurationId, bands);
    }

    const band = evaluateGradeBand(Number(row.marksObtained), bands);
    if (band?.isPass) return true;
  }

  return false;
}

const CERTIFICATE_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // Crockford-style, no 0/O/1/I ambiguity.
const CERTIFICATE_CODE_GROUP_LENGTH = 4;
const CERTIFICATE_CODE_GROUPS = 4; // 16 random characters total, grouped for readability.

/**
 * Opaque, non-sequential, cryptographically random certificate code (never
 * a counter/sequence — see this file's module comment). 16 characters drawn
 * from a 32-symbol alphabet is ~80 bits of entropy, grouped into
 * hyphen-separated 4-character blocks (e.g. "AB3D-7HKL-9MNP-Q2ST") purely
 * for human readability on a printed/PDF certificate — the grouping carries
 * no meaning and is not parsed back apart anywhere.
 */
function generateCertificateCode(): string {
  const totalChars = CERTIFICATE_CODE_GROUP_LENGTH * CERTIFICATE_CODE_GROUPS;
  const bytes = randomBytes(totalChars);
  let chars = "";
  for (let i = 0; i < totalChars; i += 1) {
    chars += CERTIFICATE_CODE_ALPHABET[bytes[i] % CERTIFICATE_CODE_ALPHABET.length];
  }
  const groups: string[] = [];
  for (let i = 0; i < CERTIFICATE_CODE_GROUPS; i += 1) {
    groups.push(chars.slice(i * CERTIFICATE_CODE_GROUP_LENGTH, (i + 1) * CERTIFICATE_CODE_GROUP_LENGTH));
  }
  return groups.join("-");
}

// Generous on purpose, same reasoning as student-payments.ts's
// MAX_INSERT_ATTEMPTS: each attempt is a full fresh transaction, so erring
// high costs little against the astronomically low real collision odds.
const MAX_INSERT_ATTEMPTS = 20;

export type ListCertificatesResult =
  | { ok: true; certificates: CertificateRecord[]; canManage: boolean }
  | { ok: false; error: CertificateActionError };

/** Academy-scoped read, optionally narrowed to one student and/or batch.
 * Available to every non-"none" permission level (including Trainer's
 * "view") — support for a later, separate item's `/academy/certificates`
 * UI is out of scope for this wave, but the read path itself is needed now
 * so that UI has something to call. */
export async function listCertificates(
  actorContext: AuthContext,
  filters: { studentId?: string; batchId?: string } = {},
): Promise<ListCertificatesResult> {
  const resolved = await resolveCertificatesAccess(actorContext);
  if (!resolved.ok) return resolved;
  const { academyId, permissionLevel } = resolved.access;

  const conditions = [eq(certificates.academyId, academyId)];
  if (filters.studentId) {
    conditions.push(eq(certificates.studentId, filters.studentId));
  }
  if (filters.batchId) {
    conditions.push(eq(certificates.batchId, filters.batchId));
  }

  const rows = await db
    .select()
    .from(certificates)
    .where(and(...conditions));

  return {
    ok: true,
    certificates: rows.map(toCertificateRecord),
    canManage: canManage(permissionLevel),
  };
}

export type GetCertificateResult =
  | { ok: true; certificate: CertificateRecord }
  | { ok: false; error: CertificateActionError };

/** Tenant-scoped single read. IDOR-safe: nonexistent or cross-academy id
 * both return the identical generic `not_found` — same convention as
 * lib/academies/student-payments.ts's `getReceipt`. This is the
 * *internal, authenticated* lookup (DESIGN.md §9.7's "Certificate
 * Verification (internal lookup)" row); the public unauthenticated lookup
 * is `verifyCertificate`, further down this file. */
export async function getCertificate(
  actorContext: AuthContext,
  certificateId: string,
): Promise<GetCertificateResult> {
  const resolved = await resolveCertificatesAccess(actorContext);
  if (!resolved.ok) return resolved;
  const { academyId } = resolved.access;

  const parsedId = z.string().uuid().safeParse(certificateId);
  if (!parsedId.success) {
    return { ok: false, error: CERTIFICATE_NOT_FOUND };
  }

  const [row] = await db
    .select()
    .from(certificates)
    .where(and(eq(certificates.id, certificateId), eq(certificates.academyId, academyId)))
    .limit(1);
  if (!row) {
    return { ok: false, error: CERTIFICATE_NOT_FOUND };
  }

  return { ok: true, certificate: toCertificateRecord(row) };
}

export type IssueCertificateResult =
  | { ok: true; certificate: CertificateRecord }
  | { ok: false; error: CertificateActionError };

/**
 * PLAN.md Phase 5, Item 57 — `issueCertificate(studentId, batchId)`.
 * Certificate Lifecycle table: `Eligible -> Issued`, actor Owner/Admin/
 * Manager (`canManage`'s "full"-or-"manage" gate), "blocked by the
 * `(student_id, batch_id)` unique constraint" — see this file's module
 * comment for the full retry-loop shape.
 */
export async function issueCertificate(
  actorContext: AuthContext,
  studentId: string,
  batchId: string,
): Promise<IssueCertificateResult> {
  const resolved = await resolveCertificatesAccess(actorContext);
  if (!resolved.ok) return resolved;
  const { academyId, membershipRole, permissionLevel } = resolved.access;

  if (!canManage(permissionLevel)) {
    return { ok: false, error: FORBIDDEN };
  }

  const parsedStudentId = z.string().uuid().safeParse(studentId);
  if (!parsedStudentId.success) {
    return { ok: false, error: STUDENT_NOT_FOUND };
  }
  const parsedBatchId = z.string().uuid().safeParse(batchId);
  if (!parsedBatchId.success) {
    return { ok: false, error: BATCH_NOT_FOUND };
  }

  const [student] = await db
    .select({ id: students.id, academyId: students.academyId })
    .from(students)
    .where(eq(students.id, studentId))
    .limit(1);
  if (!student || student.academyId !== academyId) {
    return { ok: false, error: STUDENT_NOT_FOUND };
  }

  const [batch] = await db
    .select({ id: batches.id, academyId: batches.academyId })
    .from(batches)
    .where(eq(batches.id, batchId))
    .limit(1);
  if (!batch || batch.academyId !== academyId) {
    return { ok: false, error: BATCH_NOT_FOUND };
  }

  const eligible = await isStudentEligibleForCertificate(db, academyId, studentId, batchId);
  if (!eligible) {
    return { ok: false, error: NOT_ELIGIBLE };
  }

  for (let attempt = 0; attempt < MAX_INSERT_ATTEMPTS; attempt += 1) {
    try {
      const result = await db.transaction(async (tx) => {
        const [existing] = await tx
          .select({ id: certificates.id })
          .from(certificates)
          .where(and(eq(certificates.studentId, studentId), eq(certificates.batchId, batchId)))
          .limit(1);
        if (existing) {
          return { kind: "duplicate" as const };
        }

        const certificateCode = generateCertificateCode();

        const [row] = await tx
          .insert(certificates)
          .values({
            academyId,
            studentId,
            batchId,
            certificateCode,
            issuedBy: actorContext.userId,
          })
          .returning();

        await recordAudit(
          {
            actorUserId: actorContext.userId,
            actorRole: membershipRole,
            academyId,
            action: "issueCertificate",
            entityType: "certificate",
            entityId: row.id,
            after: toCertificateRecord(row),
          },
          tx,
        );

        return { kind: "ok" as const, row };
      });

      if (result.kind === "duplicate") {
        return { ok: false, error: DUPLICATE_CERTIFICATE };
      }
      return { ok: true, certificate: toCertificateRecord(result.row) };
    } catch (err) {
      if (isUniqueViolation(err)) {
        continue; // fresh transaction, fresh code candidate, next attempt
      }
      throw err;
    }
  }

  throw new Error(
    "issueCertificate: exhausted retry attempts generating a unique certificate code.",
  );
}

export type CancelCertificateResult =
  | { ok: true; certificate: CertificateRecord }
  | { ok: false; error: CertificateActionError };

/**
 * PLAN.md Phase 5, Item 57 — `cancelCertificate`. Certificate Lifecycle
 * table: `Issued -> Cancelled`, "reason required", same Owner/Admin/Manager
 * gate as `issueCertificate`. Non-destructive: the row is never deleted,
 * only `status`/`cancelled_at`/`cancelled_by`/`cancellation_reason` are set
 * — it stays permanently visible on `/verify/[certificateCode]` afterward,
 * showing "cancelled" (DESIGN.md's Archive & Deactivation Rules table:
 * "Certificates | Owner/Admin/Manager (`cancelled` status) | ... | yes,
 * permanently (public verification) | ... | no (cancellation is
 * terminal)"). Cancelling an already-cancelled certificate is refused with
 * `already_cancelled` — the lifecycle table's own "(terminal)" row: "a
 * cancelled certificate is never re-activated."
 */
export async function cancelCertificate(
  actorContext: AuthContext,
  certificateId: string,
  reason: string,
): Promise<CancelCertificateResult> {
  const resolved = await resolveCertificatesAccess(actorContext);
  if (!resolved.ok) return resolved;
  const { academyId, membershipRole, permissionLevel } = resolved.access;

  if (!canManage(permissionLevel)) {
    return { ok: false, error: FORBIDDEN };
  }

  const parsedId = z.string().uuid().safeParse(certificateId);
  if (!parsedId.success) {
    return { ok: false, error: CERTIFICATE_NOT_FOUND };
  }

  const parsedReason = cancelCertificateReasonSchema.safeParse(reason);
  if (!parsedReason.success) {
    return {
      ok: false,
      error: {
        code: "validation",
        message: parsedReason.error.issues[0]?.message ?? "A cancellation reason is required.",
      },
    };
  }

  const result = await db.transaction(async (tx) => {
    const [certificate] = await tx
      .select()
      .from(certificates)
      .where(and(eq(certificates.id, certificateId), eq(certificates.academyId, academyId)))
      .for("update");
    if (!certificate) {
      return { kind: "not_found" as const };
    }
    if (certificate.status === "cancelled") {
      return { kind: "already_cancelled" as const };
    }

    const [updated] = await tx
      .update(certificates)
      .set({
        status: "cancelled",
        cancelledAt: new Date(),
        cancelledBy: actorContext.userId,
        cancellationReason: parsedReason.data,
      })
      .where(eq(certificates.id, certificateId))
      .returning();

    await recordAudit(
      {
        actorUserId: actorContext.userId,
        actorRole: membershipRole,
        academyId,
        action: "cancelCertificate",
        entityType: "certificate",
        entityId: certificateId,
        before: { status: certificate.status },
        after: {
          status: updated.status,
          cancelledAt: updated.cancelledAt,
          cancelledBy: updated.cancelledBy,
          cancellationReason: updated.cancellationReason,
        },
      },
      tx,
    );

    return { kind: "ok" as const, row: updated };
  });

  if (result.kind === "not_found") {
    return { ok: false, error: CERTIFICATE_NOT_FOUND };
  }
  if (result.kind === "already_cancelled") {
    return { ok: false, error: ALREADY_CANCELLED };
  }
  return { ok: true, certificate: toCertificateRecord(result.row) };
}

// ---------------------------------------------------------------------
// Item 62 — public, unauthenticated verification
// ---------------------------------------------------------------------

export interface PublicCertificateVerification {
  studentName: string;
  programName: string;
  issuedAt: Date;
  status: "valid" | "cancelled";
}

export interface VerifyCertificateError {
  code: "not_found" | "rate_limited";
  message: string;
}

export type VerifyCertificateResult =
  | { ok: true; certificate: PublicCertificateVerification }
  | { ok: false; error: VerifyCertificateError };

// Deliberately generic and identical for every failure mode (malformed
// code, well-formed-but-nonexistent code, cancelled-but-real code is NOT
// this — a cancelled certificate is `ok: true` with status "cancelled",
// per PLAN.md: "the verification endpoint's only 'not found' case is a
// genuinely nonexistent code, never a cancelled one").
const VERIFY_NOT_FOUND: VerifyCertificateError = {
  code: "not_found",
  message: "No certificate was found for this code.",
};

// Deliberately its own distinct code/message from VERIFY_NOT_FOUND — per
// this item's brief, a rate-limited response and a genuine not-found are
// not required to look identical to each other (only real-vs-fake codes
// must be indistinguishable, since a rate-limit response never depends on
// whether the submitted code happens to be real). Still generic: it never
// hints at whether *this* IP's history includes a real or fake code.
const VERIFY_RATE_LIMITED: VerifyCertificateError = {
  code: "rate_limited",
  message: "Too many verification attempts. Please try again later.",
};

const certificateCodeInputSchema = z.string().trim().min(1).max(64);

/**
 * PLAN.md Phase 5, Item 62 — public `verifyCertificate(certificateCode,
 * ip)`. See this file's module comment ("`verifyCertificate` — intentionally
 * NOT tenant-scoped") for the full reasoning on cross-academy lookup,
 * closed-academy behavior, and the choice not to log failed lookups.
 *
 * Returns ONLY the four public-safe fields PLAN.md/DESIGN.md name — student
 * name, program name, issue date, status — never any internal id
 * (certificate/student/batch/academy/user), never any other student field
 * (email/phone/address/etc.), and never any academy-level detail.
 *
 * Rate-limited per IP via lib/academies/certificate-verify-rate-limit.ts's
 * `checkCertificateVerifyRateLimit` (PLAN.md: "verification rate-limited and
 * logged") — checked before any DB work, same convention as `signIn`'s own
 * rate-limit check. A rate-limited call returns the distinct `rate_limited`
 * error rather than `not_found`; see `VERIFY_RATE_LIMITED`'s own comment for
 * why that distinction is safe to expose.
 */
export async function verifyCertificate(
  certificateCode: string,
  ip: string,
  userAgent?: string,
): Promise<VerifyCertificateResult> {
  // Checked (and incremented) before any parsing/DB work — same convention
  // as signIn's own rate-limit check in lib/auth/actions.ts — so a flood of
  // requests against this public, unauthenticated endpoint is rejected
  // cheaply regardless of whether the submitted code is even well-formed.
  const rateLimit = await checkCertificateVerifyRateLimit(ip);
  if (!rateLimit.allowed) {
    return { ok: false, error: VERIFY_RATE_LIMITED };
  }

  const parsedCode = certificateCodeInputSchema.safeParse(certificateCode);
  if (!parsedCode.success) {
    return { ok: false, error: VERIFY_NOT_FOUND };
  }

  const [row] = await db
    .select({
      id: certificates.id,
      status: certificates.status,
      issuedAt: certificates.issuedAt,
      studentFullName: students.fullName,
      programName: programs.name,
    })
    .from(certificates)
    .innerJoin(students, eq(certificates.studentId, students.id))
    .innerJoin(batches, eq(certificates.batchId, batches.id))
    .innerJoin(courses, eq(batches.courseId, courses.id))
    .innerJoin(programs, eq(courses.programId, programs.id))
    .where(eq(certificates.certificateCode, parsedCode.data))
    .limit(1);

  if (!row) {
    return { ok: false, error: VERIFY_NOT_FOUND };
  }

  // Logged only for a code that resolves to a real certificate — see this
  // file's module comment on why a failed lookup is never logged.
  await db.insert(certificateVerifications).values({
    certificateId: row.id,
    ip,
    userAgent,
  });

  return {
    ok: true,
    certificate: {
      studentName: row.studentFullName,
      programName: row.programName,
      issuedAt: row.issuedAt,
      status: row.status === "cancelled" ? "cancelled" : "valid",
    },
  };
}
